[buildPlans.runeweaver_i]
family = "Runeweaver I"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.runeweaver_i.variants.design]
capital-a = "curly-serifless"
capital-g = "toothless-corner-serifless-capped"
capital-q = "detached-bend-tailed"
capital-r = "standing"
capital-v = "curly"
capital-w = "curly"
i = "serifed-asymmetric"
l = "serifed-asymmetric"
turn-v = "curly"
lower-alpha = "crossing"
lower-iota = "flat-tailed"
lower-lambda = "curly"
lower-mu = "tailless"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-capital-u = "curly"
cyrl-capital-ya = "standing-open"
cyrl-ya = "standing-open"
zero = "dotted"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "closed"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "curly-serifed"
eight = "two-circles"
nine = "closed-contour"
asterisk = "turn-hex-low"
ampersand = "upper-open"
at = "fourfold-solid-inner"
dollar = "interrupted"
percent = "rings-segmented-slash"

    [buildPlans.runeweaver_i.ligations]
    inherits = "haskell"
    disables = []
    enables = ["exeq-dotted",
               "tildeeq",
               "exeqeq",
               "exeqeq-dotted",
               "eqeqeq",
               "eqslasheq",
               # "brst",
               "html-comment"
              ]

    [buildPlans.runeweaver_i.metric-override]
    dotSize = 'blend(weight, [100, 75], [200, 85], [300, 95], [400, 105], [500, 115], [600, 125], [700, 135], [800, 145], [900, 150])'
    periodSize = 'blend(weight, [100, 90], [200, 100], [300, 110], [400, 120], [500, 130], [600, 140], [700, 150], [800, 160], [900, 170])'

[buildPlans.runeweaver_i.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
