[buildPlans.runeweaver]
family = "Runeweaver"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.runeweaver.variants]
inherits = "ss14"

[buildPlans.runeweaver.variants.design]
capital-a = "curly-serifless"
capital-d = "standard-serifless"
capital-g = "toothless-corner-serifless-capped"
capital-k = "curly-serifless"
capital-q = "detached-bend-tailed"
capital-r = "curly"
capital-v = "curly"
capital-w = "curly"
k = "curly-serifless"
l = "serifed"
r = "serifless"
v = "curly"
w = "straight-vertical-sides"
long-s = "bent-hook"
eszet = "sulzbacher"
turn-v = "curly"
lower-alpha = "crossing"
lower-delta = "rounded"
capital-gamma = "serifless"
lower-iota = "flat-tailed"
lower-lambda = "curly"
lower-mu = "tailless"
lower-xi = "flat-top"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-en = "serifless"
cyrl-ef = "serifless"
cyrl-che = "standard"
cyrl-capital-u = "straight"
cyrl-capital-ya = "standing-open"
cyrl-ya = "standing-open"
cyrl-yeri = "corner"
cyrl-yery = "corner"
zero = "dotted-oval"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
six = "straight-bar"
seven = "curly-serifed"
eight = "crossing-asymmetric"
nine = "straight-bar"
tilde = "low"
asterisk = "turn-hex-low"
underscore = "high"
pilcrow = "high"
caret = "medium"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
ampersand = "upper-open"
at = "fourfold-solid-inner"
dollar = "interrupted"
cent = "open"
percent = "dots"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
punctuation-dot = "round"
diacritic-dot = "round"

    [buildPlans.runeweaver.ligations]
    inherits = "haskell"
    disables = ["plusplus"]
    enables = ["exeq-dotted",
               "tildeeq",
               "exeqeq",
               "exeqeq-dotted",
               "eqeqeq",
               "eqslasheq",
               "brst",
               "html-comment"
              ]

    [buildPlans.runeweaver.metric-override]
    dotSize = 'blend(weight, [100, 75], [200, 85], [300, 95], [400, 105], [500, 115], [600, 125], [700, 135], [800, 145], [900, 150])'
    periodSize = 'blend(weight, [100, 90], [200, 100], [300, 110], [400, 120], [500, 130], [600, 140], [700, 150], [800, 160], [900, 170])'

[buildPlans.runeweaver.weights.light]
shape = 450
menu = 450
css = 450

[buildPlans.runeweaver.weights.regular]
shape = 550
menu = 550
css = 550

[buildPlans.runeweaver.weights.medium]
shape = 575
menu = 575
css = 575

[buildPlans.runeweaver.weights.bold]
shape = 850
menu = 850
css = 850

[buildPlans.runeweaver.weights.heavy]
shape = 925
menu = 925
css = 925

[buildPlans.runeweaver.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
